		<div id="layout-text">
			<h1>What is Meie Raha?</h1>
			<p class="intro">Annual state budget is a complicated thing. The official Budget Bill is made up of long tables  that do little to explain how the taxpayers' money is spent. Meie Raha &mdash; Estonian for "Our Money" &mdash; shows  major  income and expenditure  articles  at a glance, structured by government functions.</p>
          <div>
            	<div class="ico">
                	<img src="img/ico-mr.png" alt="meieraha" />
                </div>
                <div class="text">
            		<h2>Interactive visualization</h2>
					<p>The visualization shows two sides of the equation — income (mostly taxes) and expenditure by category. The size of bubbles is proportional to the size of budget items. This simple visual helps to compare the sums. One can click on a bubble to see cost articles within each budget heading. Or try dragging the outline of a bubble to see how manipulating different sums results in the balance of the budget. Ideally, every budget needs to be balanced, so the changes you make on the spending sides should be balanced on the income side!</p>
                </div>
            	<div class="clear"> </div>
            </div>
            <div>
            	<div class="ico">
                	 <img src="img/ico-garage48.png" alt="garage48" style="opacity:0.6" />
                </div>
                <div class="text">
           			<h2>The team</h2>
					<p>Meie Raha was created by a team of volunteers during 48 hours at a local hackathon Garage48 and has been in development ever since. The project is non-profit and has not been funded by any political group. The Garage48 team consisted of: Rene Lasseron, Tanel Kärp, Helena Rebane, Konstantin Tretjakov, Martin Grüner, Reigo Kinusar, Hille Hinsberg and Hegle Sarapuu. Expert knowledge on budgeting was offered by prof. Paul Tammert and ex. member of the parliament's finance committee Toomas Trapido.</p>
                </div>
                <div class="clear"> </div>
            </div>
            <div>
            	<div class="ico"> &nbsp; </div>
                <div class="text">
           			<h2>Meie Raha on Facebook</h2>
					<!-- FB like button -->
            		<div id="fb-root"></div><script src="http://connect.facebook.net/en_US/all.js#appId=107879382636113&amp;xfbml=1"></script><fb:like href="http://www.facebook.com/MeieRaha" send="true" width="500" show_faces="true" font=""></fb:like>
                </div>
                <div class="clear"> </div>
            </div>			
            
                       
		</div><!--/#layout-text-->
