		<div id="layout-text">
			<h1>Contact Us!</h1>
			<p class="intro">Please send your comments! We appreciate your feedback and keep upgrading the site.</p>
			<p>If you have a dataset you’d like to see on the site, please contact the team directly and we shall arrange the visualisation for you.</p>
            <div>
                <div class="column">
					<h2>Contact</h2>
                    <p>
                        Hille Hinsberg<br />
        				Phone: +372 56 473 193<br />
        				E-mail: <a href="mailto:hille[ätt]praxis.ee">hille[ätt]praxis.ee</a>
                    </p>
                </div>
                <div class="column">
                	<h2>Send a message</h2>
               		<form id="emf-form" enctype="multipart/form-data" method="post" action="http://www.emailmeform.com/builder/form/Hl9DUsa1dVoTb5aeM" name="emf-form">
                        <label>Your e-mail</label>
                        <input id="element_0" name="element_0" class="validate[optional,custom[email]]" value="" size="30" type="text" />
                        <label>Title</label>
                        <input id="element_1" name="element_1" value="" size="30" class="validate[optional]" type="text" />
                        <textarea id="element_2" name="element_2" cols="40" rows="5" class="validate[optional]"></textarea>
                        <input name="element_counts" value="3" type="hidden" /> <input name="embed" value="forms" type="hidden" />
                        <input value="Send" type="submit" />
                    </form>
                </div>
				<div class="clear"> </div>
            </div>             
                       
		</div><!--/#layout-text-->
