		<div id="layout-text">
			<h1>State Budgeting in Estonia</h1>
			<p class="intro">Budget formulation in Estonia can be divided into two stages: the preparation of the multi-year State Budget Strategy and the preparation of the annual budget.</p>
            <div>
            	<div class="ico">
                	<img src="img/ico-uni.png" alt="government" />
                </div>
                <div class="text">
            		<h2>Estonian government</h2>
					<p>General government in Estonia is divided into three governmental levels:<br />
					· Central government (budgetary institutions, foundations, legal entities under public law, etc)<br />
					· Social security funds (Health Insurance Fund and Unemployment Fund)<br />
					· Local governments (incl. foundations)</p>
                </div>
            	<div class="clear"> </div>
            </div>
            <div>
            	<div class="ico">
                	<img src="img/ico-content.png" alt="budget011" />
                </div>
                <div class="text">
           			<h2>Budget of 2011</h2>
					<p>In addition to the central government institutions, the 2011 budget reflects local government units, Health Insurance Fund and Unemployment Insurance Fund (pension insurance is financed from the state budget) as well as budgets of  foundations and public institutions founded by the state and local governments. The government sector includes two state companies.</p>
                </div>
                <div class="clear"> </div>
            </div>
            <div>
            	<div class="ico">
                	<img src="img/norm.png" alt="balance" />
                </div>
                <div class="text">
           			<h2>Balance</h2>
            		<p>As Estonia joined the Euro zone in the beginning of 2011, balance between income and expenditures has been a very important factor when developing the state budget.</p>
            	</div><!--/.text-->
                <div class="clear"> </div>
            </div>
			
            <h1>Learn more</h1>
			<p>
                → <a href="http://pub.stat.ee/px-web.2001/I_Databas/Economy/08Finance/06Government_finances/04Revenue_expenditure_and_debt/04Revenue_expenditure_and_debt.asp" target="_blank">The general government revenues, expenditure, and debt</a><br />
                → <a href="http://www.fin.ee/index.php?id=79458" target="_blank">Estonian state budget procedures</a>
            </p>
		</div><!--/#layout-text-->

