		<div id="layout-text">
			<h1>Machine-Readable Data</h1>
			<p class="intro">The data behind Meie Raha was scraped from various resources, tables and PDF documents. The following files contain the summarization of this data on a cleaned up, machine-readable format.</p>
            <div>
                <div class="column">
                    <p class="actionlinks">
                        → <a href="data/<?=$lang?>.<?=$year?>.tulud.csv">tulud.csv</a>
                    </p>
                    <p>
                        Name: <strong>Income</strong> <br />
                        Description: <strong>The Estonian State Budget income by taxes and sums.</strong> <br />
                        Published: <strong><?=$date_published?></strong> <br />
                        Source: <strong>Meieraha.eu</strong>
                    </p>
                </div>
                <div class="column">
                    <p class="actionlinks">
                        → <a href="data/<?=$lang?>.<?=$year?>.kulud.csv">kulud.csv</a>
                    </p>
                    <p>
                        Name: <strong>Expenditures</strong> <br />
                        Description: <strong>The Estonian State Budget expenditure by categories and sums.</strong> <br />
                        Published: <strong><?=$date_published?></strong> <br />
                        Source: <strong>Meieraha.eu</strong>
                    </p>
                </div>
				<div class="clear"> </div>
            </div>  
            <br />    
            <div>
            	<div class="ico">
                	<img src="img/ico-licence.png" alt="licence" />
                </div>
                <div class="text">            
                    <h2>Open Data Commons Attribution License</h2>
                    <p>
                        Income and Expenditure databases are made available under the Open Database License: <a href="http://opendatacommons.org/licenses/odbl/" target="_blank">http://opendatacommons.org/licenses/odbl/</a>. Any rights in individual contents of the database are licensed under the Database Contents License: <a href="http://opendatacommons.org/licenses/dbcl/" target="_blank">http://opendatacommons.org/licenses/dbcl/</a>
                    </p>
                </div>
            	<div class="clear"> </div>    
            <div>
            	<div class="ico">
                	<img src="img/ico-feedback.png" alt="feedback" />
                </div>
                <div class="text"> 
            		<h2>Feedback</h2>
					<p>If you are using our collected and shared data for any purpose, <a href="feedback.html">please do let us know</a>.</p>
                </div>
            	<div class="clear"> </div> 
            </div>     
            
                   
                       
		</div><!--/#layout-text-->
