		<div id="layout-text">
			<h1>Mis on Meie Raha?</h1>
			<p class="intro">Eesti Vabariigi eelarve on pikk ja raskesti mõistetav dokument. Meie Raha on katse seda visualiseerida ja igaühele mõistetavaks teha.</p>
                        <div>
            	<div class="ico">
                	<img src="img/ico-mr.png" alt="meieraha" />
                </div>
                <div class="text">
            		<h2>Interaktiivne visualisatsioon</h2>
					<p>Eelarvel kujutame eritüübilised laekumised ja kulutused ringidena, mille suurus vastab nende omavahelisele proportsioonile eelarveridadel. Ringidele klikkides osad neist avanevad, kuvades selles sisalduva. Ringjooni hiirega sikutades saad järele proovida mõnede tululiikide mõju kuludele ning eelarvet ise tasakaalu või tasakaalust välja ajada. Kuna iga eelarve peaks olema tasakaalus, peab ka meie visuaalse eelarve tulud ja kulud peale muudatusi jääma võrdseks.</p>
                </div>
            	<div class="clear"> </div>
            </div>
            <div>
            	<div class="ico">
                	 <img src="img/ico-garage48.png" alt="garage48" style="opacity:0.6" />
                </div>
                <div class="text">
           			<h2>Tegijad</h2>
					<p>Minu Raha on valminud grupi vabatahtlike poolt Garage48 ürituse raames. Projekt on mittetulunduslik ja mittepoliitiline ning seda ei ole toetatud ühegi erakonna või poliitilise huvigrupi poolt. Garage48 tiimi kuulusid: Rene Lasseron, Tanel Kärp, Helena Rebane, Konstantin Tretjakov, Martin Grüner, Reigo Kinusar, Hille Hinsberg ja Hegle Sarapuu, eelarvega nõustab Paul Tammert.</p>
                </div>
                <div class="clear"> </div>
            </div>
            <div>
            	<div class="ico"> &nbsp; </div>
                <div class="text">
           			<h2>Meie Raha Facebookis</h2>
					<!-- FB like button -->
            		<div id="fb-root"></div><script src="http://connect.facebook.net/en_US/all.js#appId=107879382636113&amp;xfbml=1"></script><fb:like href="http://www.facebook.com/MeieRaha" send="true" width="500" show_faces="true" font=""></fb:like>
                </div>
                <div class="clear"> </div>
            </div>			
            
                       
		</div><!--/#layout-text-->

