<div id="layout-text">
			<h1>Mis on riigieelarve?</h1>
			<p class="intro">Riigieelarve on riigi ühe aasta raha ja muu vara 
sissetulekute, väljaminekute ja tehingute plaan, mille alusel kasutavad 
riiklikud institutsioonid ja Vabariigi Valitsus riigile laekuvat raha 
erinevate poliitikate elluviimiseks.</p>
			<p class="intro">Kui eelnõus on kulud esitatud asutuste lõikes, siis 
meieraha.ee annab kuludest ülevaate valdkondade lõikes. Selle jaotuse 
aluseks on valitsuse tegevusvaldkonnad ehk rahvusvaheliselt kasutatav 
COFOG klassifikatsioon.</p>
			<div>
				<div class="ico">
					<img src="static/img/ico-content.png">
				</div>
				<div class="text">
					<h2>Riigieelarve alused</h2>
					<p>Riigieelarve koostamise õiguslikeks alusteks on põhiseadus ja 
riigieelarve seadus. Tulude ja kulude sisulise kujunemise aluseks on 
riigi eelarvestrateegia ja valitsemisalade arengukavad, mis omakorda 
koondavad mitmesuguseid valdkondlikke arengukavasid. Riigieelarve eelnõu
 koostamist juhib Rahandusministeerium.</p>
				</div>
			</div>
			<div>
				<div class="ico">
					<img src="static/img/ico-uni.png">
				</div>
				<div class="text">
					<h2>Mida  riigieelarve sisaldab</h2>
					<p>Riigieelarve on otseses tähenduses riigi eelarve, ehk koondab 
ministeeriumide, põhiseaduslike institutsioonide ning Riigikantselei 
eelarved. See ei  hõlma kõikide valitsussektori asutuste eelarveid. 
Lisaks riigile kuuluvad valitsussektorisse ka kohalikud omavalitsused, 
sotsiaalkindlustusfondid (Eesti Haigekassa ja Eesti Töötukassa) ning 
mitmed muud avalik-õiguslikud institutsioonid, näiteks ülikoolid ja 
haiglad, samuti mõningad riigi omanduses olevad äriühingud ning 
sihtasutused ja mittetulundusühingud.</p>
				</div>
				<div class="clear"> </div>
			</div>
			<div>
				<div class="ico">
					<img src="static/img/norm.png">
				</div>
				<div class="text">
					<h2>Riigieelarve ja riigi raha</h2>
					<p>Vaatamata sellele, et riigieelarve sisaldab endas vaid riigi 
tulusid, kulusid ja tehinguid, on riigieelarve koostamisel vaja 
arvestada ka teiste valitsussektori institutsioonide tegevusega.</p>
					<p>NB! Eesti Haigekassale kantav eraldis  riikliku ravikindlustuse 
kulude katteks  kajastuvad riigieelarves tervishoiu valdkonnas ning on 
arvesse võetud eelarve kogusummas. Need kulud kaetakse sotsiaalmaksu 
laekumise arvelt, mis on näidatud tulude poolel.</p>
					<!-- p>NB! Töötuskindlustusmakse ei ole otseselt riigieelarve tulu ning
 Eesti Töötukassa vahendid ei ole otseselt riigieelarve osa. Teisalt on 
tööhõive valdkond ning töötutele makstavad hüvitised oluline osa riigi 
tegevusest. Seepärast näitame  töötuskindlustusmakse summa, riigieelarve
 strateegia prognoosi järgi, tulude poolel ning Töötukassa vahendid 
kulude poolel. Need summad aga ei ole eelarve kogusummas arvestatud.</p -->
				</div><!--/.text-->
				<div class="clear"> </div>
			</div>
			
			
			
			<? if ($year == 2012) { ?>
			<!-- SEE OSA AINULT 2012 PUHUL -->
			
			<div>
				<div class="ico">
					&nbsp;
					<!--img src="img/norm.png" alt="tasakaal" /-->
				</div>
				<div class="text">
					<h2>2012 aasta riigieelarve</h2>
					<p>Meieraha näitab 2012. aasta riigieelarve eelnõud ning seal 
prognoositud tulusid ja kulusid. Arvestus selle kohta, kuidas 
riigiasutuste kulud valdkondade vahel jagunevad, on tehtud koostöös 
Rahandusministeeriumiga.</p>
					<p>Riigieelarve koostatakse kassapõhise arvestusprintsiibi järgi. 
2012. aasta riigieelarve kassapõhine puudujääk on 2,7% SKP-st ehk 460,43
 miljonit eurot.</p>
					<p>Puudujääk ehk eelarve defitsiit kaetakse eelmistel aastatel kogunenud reservide või laenude abiga.</p>
				</div>
				<div class="clear"> </div>
			</div>			
			
			<div>
				<div class="ico">
					&nbsp;
					<!--img src="img/norm.png" alt="tasakaal" /-->
				</div>
				<div class="text">
					<h2>Milliseid otsuseid riigieelarve suhtes tehakse?</h2>
					<p>2012. aastal on ligi kolmveerand  (74,3%) kulude kogumahust 
plaanitud juba võetud kohustuste täitmiseks – näiteks pensionite 
väljamaksmine, Seega on poliitilised otsused võimalikud vaid väiksema 
osa suhtes kogu eelarvest. Poliitilised otsused on näiteks maksude 
tõstmine või langetamine, mõne tegevusvaldkonna kulude lisamine või 
vähendamine. Näiteks 2012. aastal kasvab riigikaitse valdkonna eelarve, 
et saavutada kaitsekulutuste määr 2% SKP-st.</p>
				</div>
				<div class="clear"> </div>
			</div>			
			
			<!-- /SEE OSA AINULT 2012 PUHUL -->
			<? } ?>
			
			
			<h1>Uuri lisaks</h1>
			<p>
				→ <a href="http://www.riigikogu.ee/index.php?id=33654" target="_blank">Kuidas valmib riigieelarve</a><br>
				→ <a href="http://www.fin.ee/riigieelarve-2011" target="_blank">Milline on riigieelarve hetkeseis</a><br>
				→ <a href="http://www.kasulik.ee/calc/rahaasjad/tee-ise-riigieelarve-2010.php" target="_blank">Katseta eelarve tulude ja kulude muutmist ka kasulik.ee keskkonnas</a>
			</p>
		</div><!--/#layout-text-->