		<div id="layout-page-footer">
        	<div class="icon icon-info"></div>
            <div id="footertext">
            	<div class="explain nomargin">
                	<div class="icon icon-hover"></div>
                    <div>
						  Move the cursor over a bubble for more info
                    </div>
                </div>
                <div class="explain">
                	<div class="icon icon-click"></div>
                    <div>
						  Click on a bubble to dig further
                    </div>                
                </div>
                <div class="explain">
                	<div class="icon icon-move"></div>
                    <div>
						  Drag bubbles around to better compare them
                    </div>                
                </div>
                <div class="explain">
                	<div class="icon icon-resize"></div>
                    <div>
						  Drag a bubble's edge to design your budget
                    </div>                
                </div>
            </div>
		</div>
   
