		<div id="layout-text">
			<h1>Data</h1>
			<p class="intro">The visualization has been based on the governmental 2013 draft state budget released on September 27, 2012. This draft will be subject to changes throughout the parliamentary works that are scheduled to be terminated in January 2013.</p>
		</div>
		<div id="layout-text">
			<h2>Images</h2>
			<p>We used following Creative Commons-licensed Flickr images as illustrations to our data:</p>
			<ul style="padding-left:0.5ex">
				<li>&bull; <a href=http://www.flickr.com/photos/agecombahia/8043446197/" target="_blank">Hospiral, fot. Manu Dias/SECOM</a> &mdash; CC BY-NC-SA agecombahia / flickr.com</li>
				<li>&bull; <a href="http://www.flickr.com/photos/14170642@N02/3703483855/" target="_blank">Warsaw, fot. Juanelos</a> &mdash; CC BY-NC-ND juanelos / flickr.com<li>
				<li>&bull; <a href="http://www.flickr.com/photos/epsos/5394616925/" target="_blank">Money, fot. epSos.de</a> &mdash; CC BY epSos.de / flickr.com</li>
				<li>&bull; <a href="http://www.flickr.com/photos/brongracz/5568415329/" target="_blank">Copernicus Science Centre, fot. Bronek Gracz</a> &mdash; CC BY brongracz / flickr.com</li>
				<li>&bull; <a href="http://www.flickr.com/photos/iks_berto/534467208/" target="_blank">Papal train in Wadowice, fot magro_kr</a> &mdash; CC BY ND magro_kr / flickr.com</li>
				<li>&bull; <a href="http://www.flickr.com/photos/basi_16816/2040617876/" target="_blank">2 zloty coin, fot. Bastian K.</a> &mdash; CC BY-NC-SA basi_16816 / flickr.com</li>
			</ul>	
            	<div class="clear"> </div>    
		<!--/#layout-text-->

