		<div id="layout-text">
			<h1>Contact Us!</h1>
			<p class="intro">We will be happy to receive your feedback. Do not hesitate to contact us in case of questions and suggestions.</p>
                <div class="column">
					<h2>Contact</h2>
                    <p>
                        Wojciech Białożyt<br />
			Centrum Cyfrowe Projekt: Polska<br/>
			Ul. Andersa 29<br/>
			00-159 Warszawa<br/>
        				Phone: +48 506 646 189<br />
        				E-mail: <a href="mailto:wbialozyt@centrumcyfrowe.pl">wbialozyt[@]centrumcyfrowe.pl</a>
                    </p>
                </div>
                <div class="column">
                	<h2>Send a message</h2>
               		<form id="emf-form" enctype="multipart/form-data" method="post" action="http://www.emailmeform.com/builder/form/FMvdbef31pGyiAQU27dWOaY" name="emf-form">
                        <label>Your e-mail</label>
                        <input id="element_0" name="element_0" class="validate[optional,custom[email]]" value="" size="30" type="text" />
                        <label>Title</label>
                        <input id="element_1" name="element_1" value="" size="30" class="validate[optional]" type="text" />
                        <textarea id="element_2" name="element_2" cols="40" rows="5" class="validate[optional]"></textarea>
                        <input name="element_counts" value="3" type="hidden" /> <input name="embed" value="forms" type="hidden" />
                        <input value="Send" type="submit" />
                    </form>
                </div>
				<div class="clear"> </div>
            </div>             
                       
		</div><!--/#layout-text-->
