		<div id="layout-text">
			<h1>The Budget</h1>
			<p class="intro">“Design your budget” interactive infographic has been prepared by Centrum Cyfrowe Projekt: Polska, digital think & do tank fostering digital dimension of public agenda. It presents the 2013 draft state budget in a simple way and give users an opportunity to design their own budgets drafts and share them in the social media.</p>
            <div>
            	<div class="ico">
                	<img src="static/img/ico-uni.png" alt="government" />
                </div>
                <div class="text">
			<p>Our project visualizes the traditional, non-performance budget. In this form it covers only part of expenditures and does not cover separate budget of, among other, following institutions:</p>
			<ul style="padding-left: 0.5ex;">
				<li>&bull; State earmarked funds</li>
				<li>&bull; Executive agencies</li>
				<li>&bull; Local governement units</li>
			</ul>
		</div>
            	<div class="clear"> </div>
            </div>
            <h2>Learn more</h2>
			<p>
                → <a href="http://www.sejm.gov.pl/sejm7.nsf/druk.xsp?nr=755" target="_blank">Budget draft bill at Sejm</a><br />
            </p>
		</div><!--/#layout-text-->

