<div id="layout-page-header">
    <ul id="title"> 
                 <li><a href="?year=<?=$year?>" class="parent">Polish Draft Budget for 2013</a>                  </li>
             </ul><ul id="main-menu"><li><a href="?page=budget" class="<?=$active['budget']?>">Budget</a></li><li><a href="?page=meieraha" class="<?=$active['meieraha']?>">About the project</a></li><li><a href="?page=data" class="<?=$active['data']?>">About the Data</a></li><li><a href="?page=feedback" class="last <?=$active['feedback']?>">Contact</a></li></ul>
</div>

