		<div id="layout-text">
			<h1>About the project</h1>
			<p class="intro">The state budget bill must be subjected to an extensive public debate. Our visualization helps to understand the complexity of the state budget ahead of the parliamentary discussions over the 2013 draft.</p>
			<p>We hope that the “Design your budget” will contribute to transparency of the public debate over the public finances issues.</p>
          <div>
            	<div class="ico">
                	<img src="static/img/ico-mr.png" alt="meieraha" />
                </div>
                <div class="text">
            		<h2>Interactive visualization</h2>
					<p>Each bubble represents the respective performance budget category. By dragging the bubbles edges, one can decide on budget priorities, balance income vs. expenditures and design his own budget.</p>
					<p>Everyone is encouraged to share his own draft budget in social media.</p>
                </div>
            	<div class="clear"> </div>
            </div>
            <div>
            	<div class="ico">
                	 <img src="static/img/ico-garage48.png" alt="garage48" style="opacity:0.6" />
                </div>
                <div class="text">
           			<h2>The team</h2>
					<p>“Design your budget” is part of the Open Government project run by Centrum Cyfrowe Projekt: Polska – <a href="http://www.centrumcyfrowe.pl/" target="_blank">>www.centrumcyfrowe.pl</p>.
					<p>We based our visualization on Meie Raha software, created for visualizing Estonian budget, during Garage48 hackathon. The project is non-profit and has not been funded by any political group. The Garage48 team consisted of: Rene Lasseron, Tanel Kärp, Helena Rebane, Konstantin Tretjakov, Martin Grüner, Reigo Kinusar, Hille Hinsberg and Hegle Sarapuu.</p>
                </div>
                <div class="clear"> </div>
            </div>
            <!--/#layout-text-->
