<div id="layout-text" style="text-align: justify;">
			<h1>Budżet</h1>
			<p class="intro">Infografika przygotowana przez Centrum Cyfrowe Projekt: Polska pokazuje w prosty sposób rządowy projekt budżetu państwa na 2013 rok oraz daje możliwość każdemu z odwiedzających serwis zaproponowania swojej wersji budżetu i podzielenia się nią w serwisach społecznościowych.</p>

			<div>
				<div class="ico">
					<img src="static/img/ico-content.png">
				</div>
				<div class="text">
					<h2>Nasza wizualizacja prezentuje budżet w układzie tradycyjnym.</h2>
					<p>Ustawa budżetowa w takim kształcie to tylko część wszystkich wydatków państwa i nie obejmuje, m.in.:</p>
					<ul style="padding-left:0.5ex;padding-top: 1ex;">
			
						<li>&bull; Państwowych funduszy celowych</li>
						<li>&bull; Agencji wykonawczych</li>	
						<li>&bull; Państwowych osób prawnych</li>
						<li>&bull; Jednostek samorzadu terytorialnego</li>
					</ul>
				</div>
			</div>
			<div>
				<div class="ico">
					<img src="static/img/ico-uni.png">
				</div>
				<div class="clear"> </div>
				<p>&nbsp;</p>
			</div>

			<h2>Więcej informacji</h2>
			<p>
				→ <a href="http://www.sejm.gov.pl/sejm7.nsf/druk.xsp?nr=755" target="_blank">Projekt ustawy budżetowej z dnia 27 września 2012 (druk sejmowy nr 755)</a><br>
			</p>
		</div><!--/#layout-text-->