		<div id="layout-text">
			<h1>Võta meiega ühendust!</h1>
			<p class="intro">Kas Sul on ettepanekuid, tagasisidet või küsimusi Meie Raha kohta? Anna meile teada ja teeme koos Meie Raha paremaks!</p>
            <div>
                <div class="column">
					<h2>Kontaktisik</h2>
                    <p>
                        Hille Hinsberg<br />
        				Tel: +372 56 473 193<br />
        				E-mail: <a href="mailto:hille[ätt]praxis.ee">hille[ätt]praxis.ee</a>
                    </p>
                </div>
                <div class="column">
                	<h2>Saada kiri</h2>
               		<form id="emf-form" enctype="multipart/form-data" method="post" action="http://www.emailmeform.com/builder/form/Hl9DUsa1dVoTb5aeM" name="emf-form">
                        <label>Sinu e-mail</label>
                        <input id="element_0" name="element_0" class="validate[optional,custom[email]]" value="" size="30" type="text" />
                        <label>Pealkiri</label>
                        <input id="element_1" name="element_1" value="" size="30" class="validate[optional]" type="text" />
                        <textarea id="element_2" name="element_2" cols="40" rows="5" class="validate[optional]"></textarea>
                        <input name="element_counts" value="3" type="hidden" /> <input name="embed" value="forms" type="hidden" />
                        <input value="Saada" type="submit" />
                    </form>
                </div>
				<div class="clear"> </div>
            </div>             
                       
		</div><!--/#layout-text-->

