		<div id="layout-page-footer">
        	<div class="icon icon-info"></div>
            <div id="footertext">
            	<div class="explain nomargin">
                	<div class="icon icon-hover"></div>
                    <div>
						Wskaż kursorem pozycję budżetową, żeby zobaczyć więcej szczegółów
                    </div>
                </div>
                <div class="explain">
                	<div class="icon icon-click"></div>
                    <div>
						Kliknij w koło, żeby zobaczyć zadania pozycji budżetowej
                    </div>                
                </div>
                <div class="explain">
                	<div class="icon icon-move"></div>
                    <div>
                                                Przesuń pozycję budżetową
                    </div>                
                </div>
                <div class="explain">
                	<div class="icon icon-resize"></div>
                    <div>
						Zmień wielkość udziału w budżecie
                    </div>                
                </div>
            </div>
		</div>
   
