		<div id="layout-page-footer">
        	<div class="icon icon-info"></div>
            <div id="footertext">
            	<div class="explain nomargin">
                	<div class="icon icon-hover"></div>
                    <div>
						Liigu hiirega mullile lugemaks selgitust
                    </div>
                </div>
                <div class="explain">
                	<div class="icon icon-click"></div>
                    <div>
						Kliki mullil et näha summasid täpsemalt
                    </div>                
                </div>
                <div class="explain">
                	<div class="icon icon-move"></div>
                    <div>
						Tiri mulle ringi et neid üksteisega võrrelda
                    </div>                
                </div>
                <div class="explain">
                	<div class="icon icon-resize"></div>
                    <div>
						Tiri mulli servast, et koostada oma eelarve
                    </div>                
                </div>
            </div>
		</div>
   
