<div id="layout-page-header">
    <ul id="title"> 
                 <li><a href="/" class="parent">Projekt budżetu państwa na 2013</a> </li>
             </ul><ul id="main-menu"><li><a href="?page=budget" class="<?=$active['budget']?>">Budżet</a></li><li><a href="?page=meieraha" class="<?=$active['meieraha']?>">O projekcie</a></li><li><a href="?page=data" class="<?=$active['data']?>">Dane</a></li><li><a href="?page=feedback" class="last <?=$active['feedback']?>">Kontakt</a></li></ul>
</div>

