		<div id="layout-text">
			<h1>Masinloetavad andmed</h1>
			<p class="intro">Meie Raha andmed on kogutud erinevatest Eesti riigieelarvega seotud tekstidest ning tabelitest. Anname teile need andmed kasutamiseks ka masinloetaval kujul.</p>
            <div>
                <div class="column">
                    <p class="actionlinks">
                        → <a href="data/<?=$lang?>.<?=$year?>.tulud.csv">tulud.csv</a>
                    </p>
                    <p>
                        Nimi: <strong>Tulud</strong> <br />
                        Kirjeldus: <strong>Eelarve tulud ja summad kroonides</strong> <br />
                        Avaldatud: <strong><?=$date_published?></strong> <br />
                        Allikas: <strong>Meieraha.eu</strong>
                    </p>
                </div>
                <div class="column">
                    <p class="actionlinks">
                        → <a href="data/<?=$lang?>.<?=$year?>.kulud.csv">kulud.csv</a>
                    </p>
                    <p>
                        Nimi: <strong>Kulud</strong> <br />
                        Kirjeldus: <strong>Eelarve kulud ja summad kroonides</strong> <br />
                        Avaldatud: <strong><?=$date_published?></strong> <br />
                        Allikas: <strong>Meieraha.eu</strong>
                    </p>
                </div>
				<div class="clear"> </div>
            </div>  
            <br />    
            <div>
            	<div class="ico">
                	<img src="img/ico-licence.png" alt="litsentsid" />
                </div>
                <div class="text">            
                    <h2>Litsents</h2>
                    <p>
                        Tulud.csv ja kulud.csv on avaldatud <strong>Avatud andmebaasi litsentsi</strong> alusel mille täisteksti leiad aadressilt <a href="http://opendatacommons.org/licenses/odbl/" target="_blank">http://opendatacommons.org/licenses/odbl/</a>. Kõik õigused andmebaasi eraldiseisvatele väärtustele on kaitstud Andmebaasi sisu litsentsiga, mille täisteksti leiad aadressil <a href="http://opendatacommons.org/licenses/dbcl/" target="_blank">http://opendatacommons.org/licenses/dbcl/</a>
                    </p>
                </div>
            	<div class="clear"> </div>    
            <div>
            	<div class="ico">
                	<img src="img/ico-feedback.png" alt="litsentsid" />
                </div>
                <div class="text"> 
            		<h2>Tagasiside</h2>
					<p>Kui kasutad meie poolt jagatud andmepakke mistahes eesmärgil, <a href="feedback.html">anna sellest palun ka meile teada</a>.</p>
                </div>
            	<div class="clear"> </div> 
            </div>     
            
                   
                       
		</div><!--/#layout-text-->
