		<div id="layout-text">
			<h1>Dane</h1>
			<p class="intro" >Nasza wizualizacja została przygotowana na podstawie <a href="http://www.mf.gov.pl/dokument.php?const=5&dzial=32&id=314184">projektu ustawy budżetowej na 2013 rok z 27 września 2012</a>. Robocza wersja budżetu państwa będzie ulegała modyfikacjom w trakcie prac parlamentu, których zakończenie zaplanowane jest na styczeń 2013 roku.</p>  		
                </div>
		<div id="layout-text">
			<h2>Ilustracje</h2>
			<p>Jako ilustracje wykorzystaliśmy zdjęcia użytkowników serwisu Flickr udostępnione na otwartych licencjach Creative Commons:</p>
			<ul style="padding-left:0.5ex">
				<li>&bull; <a href=http://www.flickr.com/photos/agecombahia/8043446197/" target="_blank">Szpital, fot. Manu Dias/SECOM</a> &mdash; CC BY-NC-SA agecombahia / flickr.com</li>
				<li>&bull; <a href="http://www.flickr.com/photos/14170642@N02/3703483855/" target="_blank">Warszawa, fot. Juanelos</a> &mdash; CC BY-NC-ND juanelos / flickr.com<li>
				<li>&bull; <a href="http://www.flickr.com/photos/epsos/5394616925/" target="_blank">Pieniądze, fot. epSos.de</a> &mdash; CC BY epSos.de / flickr.com</li>
				<li>&bull; <a href="http://www.flickr.com/photos/brongracz/5568415329/" target="_blank">Centrum Nauki Kopernik, fot. Bronek Gracz</a> &mdash; CC BY brongracz / flickr.com</li>
				<li>&bull; <a href="http://www.flickr.com/photos/iks_berto/534467208/" target="_blank">Pociąg papieski w Wadowicach, fot magro_kr</a> &mdash; CC BY ND magro_kr / flickr.com</li>
				<li>&bull; <a href="http://www.flickr.com/photos/basi_16816/2040617876/" target="_blank">Złotówka, fot. Bastian K.</a> &mdash; CC BY-NC-SA basi_16816 / flickr.com</li>
			</ul>	
                </div>
            	<div class="clear"> </div>    
		<!--/#layout-text-->
