		<div id="layout-page-footer">
        	<div class="icon icon-info"></div>
            <div id="footertext">
            	<div class="explain nomargin">
                	<div class="icon icon-hover"></div>
                    <div>
						Wskaż kursorem pozycję budżetową, żeby zobaczyć więcej szczegółów
                    </div>
                </div>
                <div class="explain">
                	<div class="icon icon-click"></div>
                    <div>
						Kliknij w koło, żeby zobaczyć zadania w obrębie poszczególnych kategorii budżetu
                    </div>                
                </div>
                <div class="explain">
                	<div class="icon icon-move"></div>
                    <div>
                                                Przeciągnij koło w inne miejsce
                    </div>                
                </div>
                <div class="explain">
                	<div class="icon icon-resize"></div>
                    <div>
						Przeciągnij róg koła, żeby zmienić przypisaną kwotę
                    </div>                
                </div>
            </div>
		</div>
   
